version: '3'

services:
  backend:
    build:
      context: '.'
      dockerfile: './build/Dockerfile'
    environment:
      - ENVIROMENT=development
    command:
      - uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
