version: '3'

services:
  backend:
    build:
      context: '.'
      dockerfile: './build/Dockerfile'
    environment:
      - ENVIROMENT=development
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./src:/src

  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=open_gym_backend
    ports:
      - 5432:5432
    volumes:
      - open_gym_postgres16_data:/var/lib/postgresql/data


volumes:
  open_gym_postgres16_data:
