[tool.poetry]
name = "open-gym-backend"
version = "0.0.0"
description = "Open Gym Backend"
authors = ["Izcar J. Muñoz Torrez <izcarmt95@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
fastapi = "^0.105.0"
uvicorn = "^0.24.0.post1"
pre-commit = "^3.6.0"



[tool.poetry.group.linter.dependencies]
black = "^23.10.0"
flake8 = "^6.1.0"
mypy = "^1.6.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 100

[tool.isort]
import_heading_stdlib = "standard library imports"
import_heading_thirdparty = "third party imports"
import_heading_firstparty = "project imports"
